server.port=8080
spring.data.mongodb.uri=${MONGODB_URI}
logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG
logging.level.org.springframework.web=INFO
spring.data.mongodb.database=raanjhanaa